#!/bin/bash

REPO=$(dirname $0)
source $REPO/setup.sh

for CFG in ${CFGS[@]}; do
    if [ -f $REPO/$CFG ]; then
        echo "Copying $CFG to ~"
        rm -f ~/.$CFG
        cat $REPO/$CFG > ~/.$CFG
        chmod 444 ~/.$CFG
    fi
done